### ISSUE TITLE
not working in debian linux with FPM socket communication

### ISSUE THREAD

**Issue by JannikZed** [renatomefi/php-fpm-healthcheck#33]
Hi guys,
We had to switch from alpine to debian linux (unfortunately). Since then, the healthcheck script is no longer running. I only receive the answer: `Make sure fcgi is installed (i.e. apk add --no-cache fcgi). Aborting.` 
I'm running the script with: `FCGI_CONNECT=/var/run/socket/php5-fpm.sock php-fpm-healthcheck` 

Could we find out the reason for it?

**Comment by renatomefi** [comment]
Hey @JannikZed this error means the `fcgi` command line isn't installed, you might try this one:
https://github.com/renatomefi/php-fpm-healthcheck/blob/v0.5.0/test/Dockerfile-buster#L6

**Comment by JannikZed** [comment]
perfect! Working now :) thank you for the fast answer!
