### ISSUE TITLE
Understanding FastCGI (with Ubuntu 22.04)

### ISSUE THREAD

**Issue by jaydrogers** [renatomefi/php-fpm-healthcheck#56]
## ⏰ Background
- I am building "PHP-FPM + NGINX" and "PHP + Apache2" images with S6 Overlay 3.1.2.1

## 👉 Problem I am trying to solve
- Some users are reporting that NGINX is starting before PHP-FPM: https://community.serversideup.net/t/502-bad-gateway-on-google-cloud-run/700/3

## 🤔 My Approach to a Solution
I found this lovely project, but I am confused on what FastCGI really is and why it's a dependency for checking the status of PHP-FPM.

What I am attempting to do is:
- Start services in order, but ensure each service is healthy before continuing to the next

Here is how I am starting my services:
```mermaid
graph TD;
    A[S6 Overlay] --> B[PHP-FPM];
     B[PHP-FPM] --> C[NGINX];
```

The folks over at S6 Overlay have been very helpful and pointed me in the right direction for the script side of things: https://github.com/just-containers/s6-overlay/issues/482

Now I just need to get that "definition of healthy" with an exit code of 0.

That's when I found this project and saw the dependency for FastCGI.

I googled "Install FastCGI Ubuntu 22.04" and this was the first result: https://installati.one/ubuntu/22.04/fcgiwrap/

## 👉 My Problem
Even with having `fcgiwrap` installed, I am getting this error:

<img width="1542" alt="Screen Shot 2022-09-22 at 12 27 53" src="https://user-images.githubusercontent.com/3174134/191815862-adc8b111-c94f-4fe3-af02-dbe4e40b381a.png">

**Error:**
```
Make sure fcgi is installed (i.e. apk add --no-cache fcgi). Aborting.
```

## 👨‍💻 My Source Code
I have all my source code available on GitHub: https://github.com/serversideup/docker-php/tree/feature/add-readiness/src

**Note:** The `fpm-nginx` image is built from the `fpm` image (so you understand the image dependency and what's included).

## ❓ Questions
1.  Is there a lightweight way to run this FastCGI server on Ubuntu 22.04 without it installing a bunch of other things in my Docker Image?

Thanks for all your hard work! This project is incredible!! 🤩

**Comment by wandersonwhcr** [comment]
Hello @jaydrogers, ty for using this project :heart: 

I'll debug your `Dockerfile.j2` in the next hours.

But I think `php-fpm-healthcheck` is not finding the `cgi-fcgi` command.

https://github.com/renatomefi/php-fpm-healthcheck/blob/master/php-fpm-healthcheck#L47

**Comment by jaydrogers** [comment]
Thanks!

That's definitely the issue.

I just don't know how to install `cgi-fcgi` in Ubuntu 22.04.

I appreciate all your work!

**Comment by wandersonwhcr** [comment]
OK, that was what I thought.

https://github.com/serversideup/docker-php/blob/feature/add-readiness/src/fpm/Dockerfile.j2#L31-L33

Here you install `fcgiwrap` with `--no-install-recommends` and it doesn't install `cgi-fcgi` command.

You can try it:

```console
~$ docker run -it --rm ubuntu:22.04
root@d04365db8c56:/# apt-get update -qq
root@d04365db8c56:/# apt-get install --no-install-recommends fcgiwrap -qq
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package spawn-fcgi.
(Reading database ... 4395 files and directories currently installed.)
Preparing to unpack .../spawn-fcgi_1.6.4-2_amd64.deb ...
Unpacking spawn-fcgi (1.6.4-2) ...
Selecting previously unselected package libfcgi0ldbl:amd64.
Preparing to unpack .../libfcgi0ldbl_2.4.2-2build2_amd64.deb ...
Unpacking libfcgi0ldbl:amd64 (2.4.2-2build2) ...
Selecting previously unselected package fcgiwrap.
Preparing to unpack .../fcgiwrap_1.1.0-12_amd64.deb ...
Unpacking fcgiwrap (1.1.0-12) ...
Setting up libfcgi0ldbl:amd64 (2.4.2-2build2) ...
Setting up spawn-fcgi (1.6.4-2) ...
Setting up fcgiwrap (1.1.0-12) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
root@d04365db8c56:/# cgi-fcgi 
bash: cgi-fcgi: command not found
```

But without `--no-install-recommends` it works.

```console
~$ docker run -it --rm ubuntu:22.04
root@1c5a6c8e643f:/# apt-get update -qq
root@1c5a6c8e643f:/# apt-get install fcgiwrap -qq
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package spawn-fcgi.
(Reading database ... 4395 files and directories currently installed.)
Preparing to unpack .../spawn-fcgi_1.6.4-2_amd64.deb ...
Unpacking spawn-fcgi (1.6.4-2) ...
Selecting previously unselected package libfcgi0ldbl:amd64.
Preparing to unpack .../libfcgi0ldbl_2.4.2-2build2_amd64.deb ...
Unpacking libfcgi0ldbl:amd64 (2.4.2-2build2) ...
Selecting previously unselected package fcgiwrap.
Preparing to unpack .../fcgiwrap_1.1.0-12_amd64.deb ...
Unpacking fcgiwrap (1.1.0-12) ...
Selecting previously unselected package libfcgi-bin.
Preparing to unpack .../libfcgi-bin_2.4.2-2build2_amd64.deb ...
Unpacking libfcgi-bin (2.4.2-2build2) ...
Setting up libfcgi0ldbl:amd64 (2.4.2-2build2) ...
Setting up libfcgi-bin (2.4.2-2build2) ...
Setting up spawn-fcgi (1.6.4-2) ...
Setting up fcgiwrap (1.1.0-12) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
root@1c5a6c8e643f:/# cgi-fcgi
Missing application pathname
Missing -connect <connName>
Usage:
    cgi-fcgi -f <cmdPath> , or
    cgi-fcgi -connect <connName> <appPath> [<nServers>] , or
    cgi-fcgi -start -connect <connName> <appPath> [<nServers>] , or
    cgi-fcgi -bind -connect <connName> ,
where <connName> is either the pathname of a UNIX domain socket
or (if -bind is given) a hostName:portNumber specification
or (if -start is given) a :portNumber specification (uses local host).
```

**Comment by wandersonwhcr** [comment]
Try to install package `libfcgi-bin`, it worked with `--no-install-recommends`.

```console
~$ docker run -it --rm ubuntu:22.04
root@fcb3da92936c:/# apt-get update -qq
root@fcb3da92936c:/# apt-get install --no-install-recommends libfcgi-bin -qq
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libfcgi0ldbl:amd64.
(Reading database ... 4395 files and directories currently installed.)
Preparing to unpack .../libfcgi0ldbl_2.4.2-2build2_amd64.deb ...
Unpacking libfcgi0ldbl:amd64 (2.4.2-2build2) ...
Selecting previously unselected package libfcgi-bin.
Preparing to unpack .../libfcgi-bin_2.4.2-2build2_amd64.deb ...
Unpacking libfcgi-bin (2.4.2-2build2) ...
Setting up libfcgi0ldbl:amd64 (2.4.2-2build2) ...
Setting up libfcgi-bin (2.4.2-2build2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
root@fcb3da92936c:/# cgi-fcgi 
Missing application pathname
Missing -connect <connName>
Usage:
    cgi-fcgi -f <cmdPath> , or
    cgi-fcgi -connect <connName> <appPath> [<nServers>] , or
    cgi-fcgi -start -connect <connName> <appPath> [<nServers>] , or
    cgi-fcgi -bind -connect <connName> ,
where <connName> is either the pathname of a UNIX domain socket
or (if -bind is given) a hostName:portNumber specification
or (if -start is given) a :portNumber specification (uses local host)
```

**Comment by jaydrogers** [comment]
You're incredible, thanks for your help @wandersonwhcr!

I moved forward with `libfcgi-bin` and it worked out perfectly! (only at ~124Kb too, thanks!). I greatly appreciate your work!!

## I ran into another issue, but I wanted to share the solution with you
Once I was able to get the health check to work, I started seeing an error on container start up:

```
ALERT: oops, unknown child (95) exited with code 0. Please open a bug report (https://github.com/php/php-src/issues).
```
<img width="2092" alt="Screen Shot 2022-09-23 at 12 23 19" src="https://user-images.githubusercontent.com/3174134/192023899-e34fc4f6-6be3-4a17-9a1a-b958bc74b307.png">

I am using [S6-Overlay](https://github.com/just-containers/s6-overlay), and with their new v3.x stuff they have a lot of cool stuff for dependencies and 

One of the methods for using their healthchecks is using [`s6-notifyoncheck`](https://skarnet.org/software/s6/s6-notifyoncheck.html).

In their docs they list an option:
> `-d` : _doublefork_. s6-notifyoncheck will run as the grandchild of prog... instead of its direct child. This is useful if prog... never reaps zombies it does not know it has. 

Taking a wild guess (because I know PHP-FPM has a parent and child processes), enabling `-d` prevented this message.

I'm now up and running with a solid PHP-FPM health check with S6 Overlay 🎉

Thanks for all your hard work @wandersonwhcr!
